In [6]:
import numpy as np
data = np.sin(np.arange(20).reshape(5,-1))
print(data)
# 按照列来取出每一列最大值的索引
ind = data.argmax(axis=0)
print(ind)
print(range(data.shape[1]))
# data.shape是一个数组，第一个元素是行数，第二个元素是列数
#range（4）相当于range(0,4)去迭代每一列（取不到4），而前面的ind相当于迭代每一行
data_max = data[ind,range(data.shape[1])]
print (data_max)

[[ 0.          0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155   0.6569866 ]
 [ 0.98935825  0.41211849 -0.54402111 -0.99999021]
 [-0.53657292  0.42016704  0.99060736  0.65028784]
 [-0.28790332 -0.96139749 -0.75098725  0.14987721]]
[2 0 3 1]
range(0, 4)
[0.98935825 0.84147098 0.99060736 0.6569866 ]


In [7]:
a = np.arange(0,40,10)
print(a)

# 先行扩宽成两杯，然后列也扩宽两倍
b = np.tile(a,(2,2))

print(b)

[ 0 10 20 30]
[[ 0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30]]


In [15]:
a = np.array([
    [4,3,5],
    [1,2,1]
])
print (a)

# axis=1是对行从小到大排序，0是对列从小到大排序
b = np.sort(a,axis = 1)
print(b)

a = np.array([3,5,4,6])
print ('--------------------------------------------')
# 可以求出最大值的索引，索引值从小到大
j = np.argsort(a)
print (j)

# 再传递回去a,就得到一个排序好的结果,显示的时候是这样显示,但是实际上a的值没有改变
# a[0] = a[0],a[1] = a[2],,,
print (a[j])
print (a)
# a = a[j]
# print (a)

[[4 3 5]
 [1 2 1]]
[[3 4 5]
 [1 1 2]]
--------------------------------------------
[0 2 1 3]
[3 4 5 6]
[3 5 4 6]
[3 4 5 6]
