In [1]:
import numpy as np

vector = np.array([10,43,54,23])
# 判断vector里面有没有值等于10
vector == 10  #返回是一个数组，会对ndarray里面每一个元素都进行相同的操作

array([ True, False, False, False])

In [2]:
matrix = np.array([
    [4,2,6,7],
    [7,3,7,2]
])
matrix == 6

array([[False, False,  True, False],
       [False, False, False, False]])

In [3]:
vector = np.array([10,43,54,23])
# 将得到一个布尔的ndarray
equal_to_sth = (vector == 10)
# 这个equal_to_sth可以作为索引，将我们需要的equal值取出来
print(vector[equal_to_sth])

[10]


In [4]:
matrix = np.array([
    [4,2,6,7],
    [7,3,7,2],
    [5,3,6,7]
])
equal_to_sth = (matrix[:,3] == 7)
print(equal_to_sth)
# 下列操作，将会直接定位到true的行当中
print(matrix[equal_to_sth,:])

[ True False  True]
[[4 2 6 7]
 [5 3 6 7]]


In [5]:
# 与
vector = np.array([5,43,9,23])
# 一个元素，既让他满足第一个条件，又让它满足第二个条件（这里是不可能既等于5又等于9）

equal_to_59 = (vector == 5) & (vector == 9)
print(equal_to_59)

[False False False False]


In [6]:
# 或
vector = np.array([5,43,9,23])
# 和上面同理
equal_to_59 = (vector == 5) | (vector == 9)
print(equal_to_59)

[ True False  True False]


In [7]:
# 索引赋值
vector = np.array([5,43,9,23])

equal_to_59 = (vector == 5) | (vector == 9)
vector[equal_to_59] = 7
print(vector)

[ 7 43  7 23]


In [8]:
matrix = np.array([
    [4,2,6,7],
    [7,3,7,2],
    [5,3,6,7]
])
equal_to_sth = matrix[:,3] == 2

matrix[equal_to_sth,3] = 1
print(matrix)

[[4 2 6 7]
 [7 3 7 1]
 [5 3 6 7]]


In [13]:
vector = np.array([5,43,9,23])
print(vector)
print(vector.dtype)
vector = vector.astype(float)
print(vector)
print(vector.dtype)

[ 5 43  9 23]
int32
[ 5. 43.  9. 23.]
float64


In [14]:
vector = np.array([5,43,9,23])
vector.min()

5

In [15]:
matrix = np.array([
    [4,2,6,7],
    [7,3,7,2],
    [5,3,6,7]
])
# 通过维度设定，对每一行求和
matrix.sum(axis=1)

array([19, 19, 21])

In [16]:
matrix = np.array([
    [4,2,6,7],
    [7,3,7,2],
    [5,3,6,7]
])
# 通过维度设定，对每一列求和
matrix.sum(axis=0)

array([16,  8, 19, 16])