In [2]:
import numpy as np
print(np.arange(15))
a = np.arange(15).reshape(3,5) #3行5列
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [3]:
a.shape

(3, 5)

In [4]:
# 维度
a.ndim 

2

In [9]:
a.dtype
# print(a.dtype.name)

dtype('int32')

In [10]:
a.size

15

In [11]:
# 要传入一个元祖格式，默认是float类型的
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
np.ones((2,3,4), dtype = np.int32)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [13]:
# 注意，这里一定是小于30不能够等于30，5相当于隔几个一加
np.arange(10,30,5)

array([10, 15, 20, 25])

In [14]:
np.arange(0,2,0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [15]:
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [16]:
# 引入random模块，调用random函数，2行3列，从负一到正一区间上的值
np.random.random((2,3))

array([[0.91752306, 0.49290635, 0.42905308],
       [0.23441066, 0.71401145, 0.66063843]])

In [18]:
from numpy import pi
# 在这个区间里面平均间隔地去100个数，2pi是可到达的
np.linspace(0 , pi*2 ,100)

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

In [20]:
a = np.array([23,54,75,23])
b = np.arange(4)
c = a - b
print(c)
c = c - 1
print(c)
b**2 #这个是乘方的意思，就是几次方
print(b**2)
print(a<45)

[23 53 73 20]
[22 52 72 19]
[0 1 4 9]
[ True False False  True]


In [22]:
A = np.array([
    [1,1],
    [0,1]
])
B = np.array([
    [2,0],
    [3,4]
])
# 对应位置相乘,星乘
print(A*B)
# 矩阵乘法,点乘,行乘以列
print(A.dot(B))
print(np.dot(A,B))

[[2 0]
 [0 4]]
[[5 4]
 [3 4]]
[[5 4]
 [3 4]]
