In [1]:
import numpy as np

B = np.arange(3)

# 表示e的多少次幂
print(np.exp(B))
# 表示对B的每个元素求根
print(np.sqrt(B))

[1.         2.71828183 7.3890561 ]
[0.         1.         1.41421356]


In [2]:
# 矩阵变换
# 注意：random生成的val是-1到1区间的，floor是向下取整
a = np.floor(10*np.random.random((3,4)))
print(a)
print("---------------------------------------------")
# 把矩阵拉平，将矩阵拉平为一个向量，（按照每一行拉平）
print(a.ravel())

# 如果shape其中一个值确定，另一个值指定为-1，那么将会自动计算
# a.reshape(2,-1)
# 不能只打印a，因为这里返回的是一个新的矩阵，并不是把a的矩阵已经变换了
print(a.reshape(-1,6))
print("---------------------------------------------")
a.shape = (2,6)
print(a)
print("---------------------------------------------")
# 转置，第一列变成第一行，诸如此类
print(a.T)
print("---------------------------------------------")
a.reshape(4,-1)
print(a)

[[2. 2. 3. 1.]
 [7. 4. 7. 0.]
 [3. 8. 6. 8.]]
---------------------------------------------
[2. 2. 3. 1. 7. 4. 7. 0. 3. 8. 6. 8.]
[[2. 2. 3. 1. 7. 4.]
 [7. 0. 3. 8. 6. 8.]]
---------------------------------------------
[[2. 2. 3. 1. 7. 4.]
 [7. 0. 3. 8. 6. 8.]]
---------------------------------------------
[[2. 7.]
 [2. 0.]
 [3. 3.]
 [1. 8.]
 [7. 6.]
 [4. 8.]]
---------------------------------------------
[[2. 2. 3. 1. 7. 4.]
 [7. 0. 3. 8. 6. 8.]]


In [3]:
# 矩阵拼接
a = np.floor(10*np.random.random((2,2)))
b = np.floor(10*np.random.random((2,2)))

print(a)
print(b)
# 横着拼接,horizontal
print(np.hstack((a,b)))
# 竖着拼接,vertical
print(np.vstack((a,b)))

[[4. 7.]
 [6. 6.]]
[[3. 1.]
 [0. 4.]]
[[4. 7. 3. 1.]
 [6. 6. 0. 4.]]
[[4. 7.]
 [6. 6.]
 [3. 1.]
 [0. 4.]]


In [16]:
# 切分，要切什么，切成几份
a = np.floor(10*np.random.random((2,12)))
print(a)
# 横着切分（这里是随机的均匀切分）
print(np.hsplit(a,3))
# 竖着切分（这里是随机的均匀切分）
a = a.reshape(12,-1)
print(a)
print(np.vsplit(a,2))

print("------------------------------------")
a = a.reshape(2,12)
print(a)
# 取3，取不到4，取前，取不到后，这里是按照行切分
print(np.hsplit(a,(3,4)))
print("------------------------------------")
a = a.T
print(a)
print(np.vsplit(a,(3,4)))

[[0. 9. 3. 7. 2. 9. 6. 8. 8. 0. 7. 3.]
 [0. 4. 5. 5. 5. 1. 1. 3. 8. 7. 3. 3.]]
[array([[0., 9., 3., 7.],
       [0., 4., 5., 5.]]), array([[2., 9., 6., 8.],
       [5., 1., 1., 3.]]), array([[8., 0., 7., 3.],
       [8., 7., 3., 3.]])]
[[0. 9.]
 [3. 7.]
 [2. 9.]
 [6. 8.]
 [8. 0.]
 [7. 3.]
 [0. 4.]
 [5. 5.]
 [5. 1.]
 [1. 3.]
 [8. 7.]
 [3. 3.]]
[array([[0., 9.],
       [3., 7.],
       [2., 9.],
       [6., 8.],
       [8., 0.],
       [7., 3.]]), array([[0., 4.],
       [5., 5.],
       [5., 1.],
       [1., 3.],
       [8., 7.],
       [3., 3.]])]
------------------------------------
[[0. 9. 3. 7. 2. 9. 6. 8. 8. 0. 7. 3.]
 [0. 4. 5. 5. 5. 1. 1. 3. 8. 7. 3. 3.]]
[array([[0., 9., 3.],
       [0., 4., 5.]]), array([[7.],
       [5.]]), array([[2., 9., 6., 8., 8., 0., 7., 3.],
       [5., 1., 1., 3., 8., 7., 3., 3.]])]
------------------------------------
[[0. 0.]
 [9. 4.]
 [3. 5.]
 [7. 5.]
 [2. 5.]
 [9. 1.]
 [6. 1.]
 [8. 3.]
 [8. 8.]
 [0. 7.]
 [7. 3.]
 [3. 3.]]
[array([[0., 0.],
       [9

In [5]:
# 复制
a = np.arange(12)
b = a
print(b is a)
b.shape = 3,4
print(a.shape)
# 名字不同，指向同一块内存空间
print(id(a))
print(id(b))

True
(3, 4)
2114065278816
2114065278816


In [7]:
c = a.view() #视频里面说是浅复制
print(c is a)
c.shape = 2,6
print(a.shape)
c[0,4] = 1234
# 指向不同，但是共用一套值
print(a)
print(id(a))
print(id(c))

False
(3, 4)
[[   0    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]
2114065278816
2114065279216


In [8]:
# 真正的复制、拷贝，深拷贝
d = a.copy()
print(d is a)
d[0,0] = 9999
print(d)
print(a)

False
[[9999    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]
[[   0    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]
